blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/futureharmony/storagebrowser/discussions
    about: Please ask questions and discuss features here.
